service: heygen-queue

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 256
  timeout: 30
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

package:
  individually: true

functions:
  helloWorld:
    handler: index.helloWorld
    events:
      - http:
          path: hello
          method: get
          cors: true

plugins:
  - serverless-plugin-typescript

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.json"
