service: heygen-queue

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 256
  timeout: 30
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    HEYGEN_VIDEOS_TABLE: HeygenVideosTable-${sls:stage}
    HEYGEN_API_KEY: ${env:HEYGEN_API_KEY}
    HEYGEN_MAX_CONCURRENCY: 3
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/HeygenVideosTable-${sls:stage}
        - Effect: Allow
          Action:
            - events:PutRule
            - events:PutTargets
            - events:RemoveTargets
            - events:DeleteRule
            - events:DescribeRule
            - events:ListRules
            - events:ListTargetsByRule
          Resource: "*"
  apiGateway:
    apiKeys:
      - heygen-queue-prod-key

package:
  individually: true

functions:
  helloWorld:
    handler: index.helloWorld
    events:
      - http:
          path: hello
          method: get
          cors: true
  enqueueHandler:
    handler: index.enqueueHandler
    events:
      - http:
          path: enqueue
          method: post
          cors: true
          private: true
  worker:
    handler: index.workerHttpHandler
    events:
      - http:
          path: worker
          method: post
          cors: true
          private: true
      - schedule:
          rate: rate(1 minute)
          enabled: true
  poll:
    handler: index.pollHttpHandler
    events:
      - http:
          path: poll
          method: post
          cors: true
          private: true
      - schedule:
          rate: rate(1 minute)
          enabled: true

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node18
    platform: node
    concurrency: 10

resources:
  Resources:
    HeygenVideosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: HeygenVideosTable-${sls:stage}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
