service: upload-to-s3

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 256
  timeout: 30
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:GetObject
            - s3:ListBucket
            - s3:HeadBucket
          Resource:
            - "arn:aws:s3:::*"
            - "arn:aws:s3:::*/*"

package:
  individually: true

functions:
  uploadToS3:
    handler: index.handler
    events:
      - http:
          path: upload
          method: post
          cors: true

plugins:
  - serverless-plugin-typescript

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.json"
